[package]
name = "hls_m3u8"
version = "0.2.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "HLS m3u8 parser/generator"
homepage = "https://github.com/sile/hls_m3u8"
repository = "https://github.com/sile/hls_m3u8"
readme = "README.md"
license = "MIT"
keywords = ["hls", "m3u8"]
edition = "2018"
categories = ["parser"]

[badges]
travis-ci = {repository = "sile/hls_m3u8"}
codecov = {repository = "sile/hls_m3u8"}

[dependencies]
getset = "0.0.8"
failure = "0.1.5"
derive_builder = "0.7.2"
url = "2.1.0"
chrono = "0.4.9"

[dev-dependencies]
clap = "2"
