[package]
name = "hls_m3u8"
version = "0.2.1"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "HLS m3u8 parser/generator"
homepage = "https://github.com/sile/hls_m3u8"
repository = "https://github.com/sile/hls_m3u8"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["hls", "m3u8"]
edition = "2018"
categories = ["parser"]

[badges]
codecov = { repository = "sile/hls_m3u8" }
travis-ci = { repository = "sile/hls_m3u8" }

[dependencies]
chrono = "0.4"
derive_builder = "0.9"
derive_more = "0.99"
hex = "0.4"
shorthand = "0.1"
strum = { version = "0.17", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "0.6"
